### ISSUE TITLE
mAP of CenterNet with HarDNet68 

### ISSUE THREAD

**Issue by cao-nv** [PingoLH/CenterNet-HarDNet#3]
Hi, CenterNet with your HarDNet as the backbone worked well on COCO! 
Have you tried HarDNet68? If yes, could you provide mAPs of that variant? 
Thank you and sorry if I missed something.

**Comment by PingoLH** [comment]
Hi, sorry that we haven't had a chance to train CenterNet-HarDNet68, but I will definitely share it once we have it.

**Comment by cao-nv** [comment]
> Hi, sorry that we haven't had a chance to train CenterNet-HarDNet68, but I will definitely share it once we have it.

Thank you! Looking forward to your results!
