### ISSUE TITLE
Int8

### ISSUE THREAD

**Issue by niaoyu** [PingoLH/CenterNet-HarDNet#4]
Hi, I tried your fp16 version which was great!

However, when I tried int8 calib, trt will not get batch from the Int8Calib class.

The only difference would be "adding ctdet to onnx". Do you have any suggestions?

**Comment by PingoLH** [comment]
Hi, we haven't had a chance to try int8 calibration. Could you talk a little bit more about it? Did you try to do custom calibration by following [Nvidia's suggestion](https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleINT8/README.md)? then IInt8EntropyCalibrator couldn't find the batch dim or couldn't get it to work with BatchStream::getBatch()? Thanks!

**Comment by niaoyu** [comment]
> Hi, we haven't had a chance to try int8 calibration. Could you talk a little bit more about it? Did you try to do custom calibration by following [Nvidia's suggestion](https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleINT8/README.md)? then IInt8EntropyCalibrator couldn't find the batch dim or couldn't get it to work with BatchStream::getBatch()? Thanks!

Hi, I figured out the reason from nvidia forums.
https://forums.developer.nvidia.com/t/tensorrt-7-1-silently-disable-int8-calibration-if-network-contains-bool-tensor/142246

I try to use another op instead of "equal" and it works fine. (Although there is no improvements from fp16 to int8)

Best wishes!
